package kai.configuration

import kai.conversation.conversation.ConversationLoader
import kai.kaibrain.emotion.ToneRecognition
import java.io.File

class Kai {
    enum class KaiFallbackFeatures{
        BaseConversation, AutogeneratedConversation, Math, WikiSearch, Spotify, ConversationRevive, AskAbout
    }

    enum class KaiFeatureSet{
        BaseConversation, AutogeneratedConversation, Math, WikiSearch, Spotify, AskAbout, Reminders, AutoLearn, ConversationRevive
    }

    data class KaiBuilder(val configurationName : String){
        var input : String = "default"
        var response : String = "default"
        var projectPath : File = File("/kaiProject")
        var conversationHolder : Int = 0
        var conversationStatus : Boolean = false
        var conversationMethodSuccessFull : Boolean = false
        var conversationCounter = 1
        var conversationEmotionTone : ToneRecognition.Emotion = ToneRecognition.Emotion.Normal
        var fallbackOrder : ArrayList<KaiFallbackFeatures> = arrayListOf<KaiFallbackFeatures>(KaiFallbackFeatures.BaseConversation, KaiFallbackFeatures.AutogeneratedConversation,
                KaiFallbackFeatures.Math, KaiFallbackFeatures.WikiSearch, KaiFallbackFeatures.Spotify,
                KaiFallbackFeatures.ConversationRevive, KaiFallbackFeatures.AskAbout)
    }

    fun runConversation(builder : KaiBuilder){
        ConversationLoader().conversationSystem(builder)
    }

    fun addPlugin(function: () -> Unit) {

    }
}
